@startuml
title Despliegue
node Node.js {
interface HTTP
component Express
component Servicio
artifact endpoint.js <<boundary>>
artifact controller.js <<control>>
component "filesystem" as fs
}

node "MySQL server" as MySQL {
database dbCaballos <<entity>>
artifact datos.json <<tabla>>
}

HTTP -- Servicio
Servicio <.. endpoint.js: <<manifests>>
Express <.. endpoint.js: <<uses>>

endpoint.js *-- controller.js

controller.js ..> fs: <<uses>>

fs -0- dbCaballos: SQL

dbCaballos <-- datos.json: <<manifests>>
@enduml
