@startuml
title Todos los pedidos GET
actor Cliente as U
boundary endpoint.js as E
control control as C

entity dbCaballos as D

U -> E: HTTP GET (path,req)
activate E
E -> E: app.get(path, (req,res))
activate E
E -> C: getdatos(req)
activate C
C -> C: Generar query

group MySQL driver
C -> D: Connect
C -> D: SQL SELECT
D -> C: Resultados
C -> C: Convertir en objeto
end

C --> E: Obj resultado
deactivate C
deactivate E
E -> E: stringify(resultado)
E --> U: res.end(resultado)
deactivate E
@enduml
